language: objective-c
os: osx
osx_image: xcode8.1
script:
- set -o pipefail && xcodebuild test -workspace 'SwiftyPaperTrail.xcworkspace' -scheme 'SwiftyPaperTrail' -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.1' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
