#!/bin/sh -e

bundle exec pod update
bundle exec pod repo update
bundle exec pod install
WORKSPACE='SwiftyPaperTrail.xcworkspace'
SCHEME='SwiftyPaperTrail'
xcodebuild -workspace $WORKSPACE -scheme $SCHEME -list
set -o pipefail && xcodebuild test -workspace $WORKSPACE -scheme $SCHEME -destination 'platform=iOS Simulator,name=iPhone 6' ONLY_ACTIVE_ARCH=NO | xcpretty
bundle exec pod lib lint
